package ru.vorobyov.FX.controllers;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.stage.Stage;
import ru.vorobyov.FX.pageCreator.FXPageCreator;
import ru.vorobyov.database.bl.DatabaseUtil;
import ru.vorobyov.database.entity.*;
import ru.vorobyov.database.service.*;

import java.io.IOException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.SQLException;

public class WelcomePageController {

    @FXML
    private Button buttonToReportCard;

    @FXML
    private Button buttonToEdit;

    static private Stage reportCardPage = null;

    @FXML
    void toReportCard(ActionEvent event) {
        try {
            Connection connection = DatabaseUtil.getConnection();
            try {
                createTables();
            } catch (SQLException e) {
                e.printStackTrace();
            }

            new FXPageCreator().createPage("/fxml\\reportCardPage.fxml", 1366, 599);
            
        } catch (IOException er) {
            er.printStackTrace();
        }
    }

    @FXML
    void toEdit(ActionEvent event) throws SQLException {
        try {
            Connection connection = DatabaseUtil.getConnection();
           /* try {
                createTables();
            } catch (SQLException e) {
                e.printStackTrace();
            }*/

            if(!new RolesService().getAll().isEmpty()) new RolesService().truncateTable();

            RolesService rolesService = new RolesService();
            rolesService.createTable();
            Roles roles = new Roles();
            roles.setLogin("Admin");
            roles.setPassword("Admin");
            new RolesService().add(roles);
            roles.setLogin("Timekeeper");
            roles.setPassword("Timekeeper");
            new  RolesService().add(roles);

            new FXPageCreator().createPage("/fxml\\loginPage.fxml", 600, 400);

        } catch (IOException er) {
            er.printStackTrace();
        }
    }

    public void createTables() throws IOException, SQLException {

        /*if(!new RolesService().getAll().isEmpty()) new RolesService().truncateTable();
        if(!new AccountingService().getAll().isEmpty()) new AccountingService().truncateTable();
        if(!new EncodingService().getAll().isEmpty()) new EncodingService().truncateTable();
        if(!new WorkerService().getAll().isEmpty()) new WorkerService().truncateTable();
        if(!new DepartmentService().getAll().isEmpty()) new DepartmentService().truncateTable();
        if(!new JobInfoService().getAll().isEmpty()) new JobInfoService().truncateTable();*/

        RolesService rolesService = new RolesService();
        rolesService.createTable();

        DepartmentService departmentService = new DepartmentService();
        departmentService.createTable();


        JobInfoService jobInfoService = new JobInfoService();
        jobInfoService.createTable();


        WorkerService workerService = new WorkerService();
        workerService.createTable();


        EncodingService encodingService = new EncodingService();
        encodingService.createTable();


        AccountingService accountingService = new AccountingService();
        accountingService.createTable();


        Roles roles = new Roles();
        roles.setLogin("Admin");
        roles.setPassword("Admin");
        new RolesService().add(roles);
        roles.setLogin("Timekeeper");
        roles.setPassword("Timekeeper");
        new RolesService().add(roles);

        Department department = new Department();
        department.setDepartment("Автоматизация антипригарных стульев");
        new DepartmentService().add(department);
        department.setDepartment("Разработка цветочных фреймворков");
        new DepartmentService().add(department);
        department.setDepartment("PR станков и горшков");
        new DepartmentService().add(department);

        JobInfo jobInfo = new JobInfo();
        jobInfo.setPosition("Повар");
        new JobInfoService().add(jobInfo);
        jobInfo.setPosition("IT-директор");
        new JobInfoService().add(jobInfo);

        Worker worker = new Worker();
        worker.setWorkerId(342);
        worker.setPreview(null);
        worker.setName("Пётр");
        worker.setLastName("Семёнов");
        worker.setBirthday(new Date(90, 3, 24));
        worker.setAge(30);
        worker.setAddress("г. Москва");
        worker.setRemoteWork(false);
        worker.setDepartment("Автоматизация антипригарных стульев");
        worker.setPosition("IT-директор");
        new WorkerService().add(worker);

        worker.setWorkerId(9382);
        worker.setPreview(null);
        worker.setName("Василий");
        worker.setLastName("Алибабаев");
        worker.setBirthday(new Date(83, 5, 23));
        worker.setAge(37);
        worker.setAddress("г. СПб");
        worker.setRemoteWork(false);
        worker.setDepartment("Автоматизация антипригарных стульев");
        worker.setPosition("Повар");
        new WorkerService().add(worker);

        Encoding encoding = new Encoding();
        encoding.setEncoding("Я");
        new EncodingService().add(encoding);
        encoding.setEncoding("Н");
        new EncodingService().add(encoding);
        encoding.setEncoding("В");
        new EncodingService().add(encoding);
        encoding.setEncoding("Рв");
        new EncodingService().add(encoding);
        encoding.setEncoding("Б");
        new EncodingService().add(encoding);
        encoding.setEncoding("К");
        new EncodingService().add(encoding);
        encoding.setEncoding("ОТ");
        new EncodingService().add(encoding);
        encoding.setEncoding("До");
        new EncodingService().add(encoding);
        encoding.setEncoding("Хд");
        new EncodingService().add(encoding);
        encoding.setEncoding("У");
        new EncodingService().add(encoding);
        encoding.setEncoding("Ож");
        new EncodingService().add(encoding);

        Accounting accounting = new Accounting();
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 1));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 2));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 3));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("В");
        accounting.setDay(new Date(120,0, 4));
        new AccountingService().add(accounting);
        accounting.setEncoding("В");
        accounting.setDay(new Date(120,0, 5));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 6));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 7));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 8));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 9));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 10));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("В");
        accounting.setDay(new Date(120,0, 11));
        new AccountingService().add(accounting);
        accounting.setEncoding("В");
        accounting.setDay(new Date(120,0, 12));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 13));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 14));
        new AccountingService().add(accounting);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 15));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 16));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 17));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("В");
        accounting.setDay(new Date(120,0, 18));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("В");
        accounting.setDay(new Date(120,0, 19));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 20));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 21));
        new AccountingService().add(accounting);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 22));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 23));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 24));
        new AccountingService().add(accounting);
        accounting.setEncoding("В");
        accounting.setDay(new Date(120,0, 25));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("В");
        accounting.setDay(new Date(120,0, 26));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 27));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 28));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 29));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 30));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 31));
        new AccountingService().add(accounting);

        accounting.setWorkerId(342);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 1));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 2));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 3));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("В");
        accounting.setDay(new Date(120,0, 4));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("В");
        accounting.setDay(new Date(120,0, 5));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 6));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 7));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 8));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 9));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 10));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("В");
        accounting.setDay(new Date(120,0, 11));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("В");
        accounting.setDay(new Date(120,0, 12));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 13));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 14));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 15));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 16));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 17));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 18));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("В");
        accounting.setDay(new Date(120,0, 19));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("В");
        accounting.setDay(new Date(120,0, 20));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 21));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 22));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 23));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 24));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 25));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("В");
        accounting.setDay(new Date(120,0, 26));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("В");
        accounting.setDay(new Date(120,0, 27));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 28));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 29));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 30));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,0, 31));
        new AccountingService().add(accounting);
        //february
        accounting.setWorkerId(342);
        accounting.setEncoding("ОТ");
        accounting.setDay(new Date(120,1, 1));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("ОТ");
        accounting.setDay(new Date(120,1, 2));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("ОТ");
        accounting.setDay(new Date(120,1, 3));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("ОТ");
        accounting.setDay(new Date(120,1, 4));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("ОТ");
        accounting.setDay(new Date(120,1, 5));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("ОТ");
        accounting.setDay(new Date(120,1, 6));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("ОТ");
        accounting.setDay(new Date(120,1, 7));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("ОТ");
        accounting.setDay(new Date(120,1, 8));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("ОТ");
        accounting.setDay(new Date(120,1, 9));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("ОТ");
        accounting.setDay(new Date(120,1, 10));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("ОТ");
        accounting.setDay(new Date(120,1, 11));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("ОТ");
        accounting.setDay(new Date(120,1, 12));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("ОТ");
        accounting.setDay(new Date(120,1, 13));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("ОТ");
        accounting.setDay(new Date(120,1, 14));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("ОТ");
        accounting.setDay(new Date(120,1, 15));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("ОТ");
        accounting.setDay(new Date(120,1, 16));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("ОТ");
        accounting.setDay(new Date(120,1, 17));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("ОТ");
        accounting.setDay(new Date(120,1, 18));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("ОТ");
        accounting.setDay(new Date(120,1, 19));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("ОТ");
        accounting.setDay(new Date(120,1, 20));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("ОТ");
        accounting.setDay(new Date(120,1, 21));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("ОТ");
        accounting.setDay(new Date(120,1, 22));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("ОТ");
        accounting.setDay(new Date(120,1, 23));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("ОТ");
        accounting.setDay(new Date(120,1, 24));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("ОТ");
        accounting.setDay(new Date(120,1, 25));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("ОТ");
        accounting.setDay(new Date(120,1, 26));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("ОТ");
        accounting.setDay(new Date(120,1, 27));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("ОТ");
        accounting.setDay(new Date(120,1, 28));
        new AccountingService().add(accounting);
        accounting.setWorkerId(342);
        accounting.setEncoding("ОТ");
        accounting.setDay(new Date(120,1, 29));
        new AccountingService().add(accounting);


        accounting.setWorkerId(9382);
        accounting.setEncoding("Б");
        accounting.setDay(new Date(120,1, 1));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Б");
        accounting.setDay(new Date(120,1, 2));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,1, 3));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,1, 4));
        new AccountingService().add(accounting);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,1, 5));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,1, 6));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,1, 7));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,1, 8));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("В");
        accounting.setDay(new Date(120,1, 9));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("В");
        accounting.setDay(new Date(120,1, 10));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,1, 11));
        new AccountingService().add(accounting);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,1, 12));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,1, 13));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,1, 14));
        new AccountingService().add(accounting);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,1, 15));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("В");
        accounting.setDay(new Date(120,1, 16));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("В");
        accounting.setDay(new Date(120,1, 17));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,1, 18));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,1, 19));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,1, 20));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,1, 21));
        new AccountingService().add(accounting);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,1, 22));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("В");
        accounting.setDay(new Date(120,1, 23));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("В");
        accounting.setDay(new Date(120,1, 24));
        new AccountingService().add(accounting);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,1, 25));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,1, 26));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,1, 27));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,1, 28));
        new AccountingService().add(accounting);
        accounting.setWorkerId(9382);
        accounting.setEncoding("Я");
        accounting.setDay(new Date(120,1, 29));
        new AccountingService().add(accounting);
    }

}